'use client';
import SimplePage from '../../components/SimplePage';
import TeacherCard from '../../components/TeacherCard';
import {demoTeachers} from '../../lib/data';
import {useMemo,useState} from 'react';
export default function Page(){
 const [subject,setSubject]=useState(''); const [gender,setGender]=useState(''); const [maxPrice,setMaxPrice]=useState(500); const [minExp,setMinExp]=useState(0); const [search,setSearch]=useState('');
 const list=useMemo(()=>demoTeachers.filter((t:any)=>{const s=(t.nameAr+' '+t.nameEn+' '+t.subjectAr+' '+t.subjectEn).toLowerCase();return (!search||s.includes(search.toLowerCase()))&&(!subject||t.subjectAr===subject||t.subjectEn===subject)&&Number(t.price)<=maxPrice&&Number(t.experience)>=minExp&&(!gender||!t.gender||t.gender===gender)}),[subject,gender,maxPrice,minExp,search]);
 const subjects=Array.from(new Set(demoTeachers.map((t:any)=>t.subjectAr)));
 return <SimplePage title="المدرسون"><div className="panel" style={{marginBottom:24}}><h3>ابحث وفلتر المدرسين</h3><div className="filterGrid"><input placeholder="اسم المدرس أو المادة" value={search} onChange={e=>setSearch(e.target.value)}/><select value={subject} onChange={e=>setSubject(e.target.value)}><option value="">كل المواد</option>{subjects.map(x=><option key={x}>{x}</option>)}</select><select value={gender} onChange={e=>setGender(e.target.value)}><option value="">النوع: الكل</option><option value="male">ذكر</option><option value="female">أنثى</option></select><label>السعر حتى {maxPrice} ر.ق<input type="range" min="50" max="500" step="10" value={maxPrice} onChange={e=>setMaxPrice(+e.target.value)}/></label><select value={minExp} onChange={e=>setMinExp(+e.target.value)}><option value="0">كل الخبرات</option><option value="3">3+ سنوات</option><option value="5">5+ سنوات</option><option value="10">10+ سنوات</option></select><button className="primary" onClick={()=>{setSubject('');setGender('');setMaxPrice(500);setMinExp(0);setSearch('')}}>مسح الفلاتر</button></div></div><p style={{marginBottom:16}}>تم العثور على {list.length} مدرس</p><div className="cards">{list.map((t:any)=><TeacherCard key={t.id} t={t}/>)}</div>{!list.length&&<div className="panel"><h3>لا توجد نتائج مطابقة</h3><p>جرّب تغيير الفلاتر.</p></div>}</SimplePage>}
